library(coefplot)
library(ggplot2)
library(ggeffects)
library(cowplot)

# Read in data
survData <- read.csv("D:/EvansLab/Final/Data/Processed/Survival/SurvivalData.csv", header = T, stringsAsFactors = F)

# Recode status
survData$dead <- ifelse(survData$STATUSCD == 2, 1, 0)

# Model: size + elevation + BA
smodel <- glm(dead ~ PREV_DRYBIO_AG + I(PREV_DRYBIO_AG^2) + I(PREV_DRYBIO_AG^3) + elev + baLive, family = "binomial", data = survData)
summary(smodel)
save(smodel, file = "D:/EvansLab/Final/Models/B/surv.rda")
pdf("D:/EvansLab/Final/Output/B/SurvivalModel.pdf")
coefplot(smodel, intercept = F)
preds <- ggpredict(smodel, terms = c("PREV_DRYBIO_AG"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Mortality vs. biomass")
preds <- ggpredict(smodel, terms = c("elev"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Mortality vs. elevation")
preds <- ggpredict(smodel, terms = c("baLive"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Mortality vs. plot BA")
dev.off()
# Publication figure
preds <- ggpredict(smodel, terms = c("PREV_DRYBIO_AG"))
A <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Mortality") + xlab("Biomass")
preds <- ggpredict(smodel, terms = c("elev"))
B <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Mortality") + xlab("Elevation")
preds <- ggpredict(smodel, terms = c("baLive"))
C <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Mortality") + xlab("Plot basal area")
all <- plot_grid(A, B, C, labels = c("A", "B", "C"), align = "hv")
save_plot("D:/EvansLab/Final/Manuscript/FigS4.png", all, base_aspect_ratio = 1.5)

# Model: size + elevation + climate
smodel <- glm(dead ~ PREV_DRYBIO_AG + elev + PPT_c + PPT_w + VPD_c + VPD_w, family = "binomial", data = survData)
smodel <- update(smodel, . ~ . - PPT_c)
smodel <- update(smodel, . ~ . - PPT_w)
smodel <- update(smodel, . ~ . - VPD_c)
smodel <- update(smodel, . ~ . + I(PREV_DRYBIO_AG^2) + I(PREV_DRYBIO_AG^3))
summary(smodel)
save(smodel, file = "D:/EvansLab/Final/Models/C/surv.rda")
pdf("D:/EvansLab/Final/Output/C/SurvivalModel.pdf")
coefplot(smodel, intercept = F)
preds <- ggpredict(smodel, terms = c("PREV_DRYBIO_AG"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Mortality vs. biomass")
preds <- ggpredict(smodel, terms = c("elev"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Mortality vs. elevation")
preds <- ggpredict(smodel, terms = c("VPD_w"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Mortality vs. VPD warm")
dev.off()
# Publication figure
preds <- ggpredict(smodel, terms = c("PREV_DRYBIO_AG"))
A <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Mortality") + xlab("Biomass")
preds <- ggpredict(smodel, terms = c("elev"))
B <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Mortality") + xlab("Elevation")
preds <- ggpredict(smodel, terms = c("VPD_w"))
C <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Mortality") + xlab("Warm-season VPD")
all <- plot_grid(A, B, C, labels = c("A", "B", "C"), align = "hv")
save_plot("D:/EvansLab/Final/Manuscript/FigS5.png", all, base_aspect_ratio = 1.5)

# Model: size + elevation + BA + climate
smodel <- glm(dead ~ PREV_DRYBIO_AG + elev + baLive + PPT_c + PPT_w + VPD_c + VPD_w, family = "binomial", data = survData)
smodel <- update(smodel, . ~ . - PPT_c)
smodel <- update(smodel, . ~ . - PPT_w)
smodel <- update(smodel, . ~ . - VPD_c)
smodel <- update(smodel, . ~ . + I(PREV_DRYBIO_AG^2))
smodel <- update(smodel, . ~ . + I(PREV_DRYBIO_AG^2) + I(PREV_DRYBIO_AG^3))
# smodel <- update(smodel, . ~ . + I(VPD_w^2) + I(VPD_w^3))
smodel <- update(smodel, . ~ . - VPD_w)
smodel <- update(smodel, . ~ . + log(VPD_w))
summary(smodel)
save(smodel, file = "D:/EvansLab/Final/Models/BC/surv.rda")
pdf("D:/EvansLab/Final/Output/BC/SurvivalModel.pdf")
coefplot(smodel, intercept = F)
preds <- ggpredict(smodel, terms = c("PREV_DRYBIO_AG"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Mortality vs. biomass")
preds <- ggpredict(smodel, terms = c("elev"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Mortality vs. elevation")
preds <- ggpredict(smodel, terms = c("baLive"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Mortality vs. plot BA")
preds <- ggpredict(smodel, terms = c("VPD_w"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Mortality vs. VPD warm")
dev.off()
# Publication figure
preds <- ggpredict(smodel, terms = c("PREV_DRYBIO_AG"))
A <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Mortality") + xlab("Biomass")
preds <- ggpredict(smodel, terms = c("elev"))
B <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Mortality") + xlab("Elevation")
preds <- ggpredict(smodel, terms = c("baLive"))
C <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Mortality") + xlab("Plot basal area")
preds <- ggpredict(smodel, terms = c("VPD_w"))
D <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Mortality") + xlab("Warm-season VPD")
all <- plot_grid(A, B, C, D, labels = c("A", "B", "C", "D"), align = "hv")
save_plot("D:/EvansLab/Final/Manuscript/FigS6.png", all, base_aspect_ratio = 1.5)