library(ggeffects)
library(ggplot2)
library(coefplot)
library(cowplot)

# Read data
grdata <- read.csv("D:/EvansLab/Final/Data/Processed/Growth/GrowthData.csv", header = T, stringsAsFactors = F)

# Create increment column
grdata$GROWTH_INCR <- grdata$DRYBIO_AG_DIFF / grdata$CENSUS_INTERVAL

# Model: size + elevation + BA
gmodel <- lm(data = grdata, GROWTH_INCR ~ DRYBIO_AG + I(DRYBIO_AG^2) + elev + baLive)
summary(gmodel)
growSD <- sd(resid(gmodel))
save(gmodel, growSD, file = "D:/EvansLab/Final/Models/B/grow.rda")
pdf("D:/EvansLab/Final/Output/B/GrowthModel.pdf")
coefplot(gmodel, intercept = F)
preds <- ggpredict(gmodel, terms = c("DRYBIO_AG"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Growth vs. biomass")
preds <- ggpredict(gmodel, terms = c("elev"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Growth vs. elevation")
preds <- ggpredict(gmodel, terms = c("baLive"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Growth vs. plot BA")
dev.off()
preds <- ggpredict(gmodel, terms = c("DRYBIO_AG"))
A <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Growth") + xlab("Biomass")
preds <- ggpredict(gmodel, terms = c("elev"))
B <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Growth") + xlab("Elevation")
preds <- ggpredict(gmodel, terms = c("baLive"))
C <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Growth") + xlab("Plot basal area")
all <- plot_grid(A, B, C, labels = c("A", "B", "C"), align = "hv")
save_plot("D:/EvansLab/Final/Manuscript/FigS1.png", all, base_aspect_ratio = 1.5)

# Model: size + elevation + climate
gmodel <- lm(data = grdata, GROWTH_INCR ~ DRYBIO_AG + elev + PPT_c + PPT_w + VPD_c + VPD_w)
gmodel <- update(gmodel, . ~ . - PPT_c)
gmodel <- update(gmodel, . ~ . - VPD_w)
gmodel <- update(gmodel, . ~ . + I(DRYBIO_AG^2))
# gmodel <- update(gmodel, . ~ . + I(VPD_c^2))
# gmodel <- update(gmodel, . ~ . + I(VPD_c^3))
# gmodel <- update(gmodel, . ~ . + I(VPD_c^4))
gmodel <- update(gmodel, . ~ . - VPD_c) # VPD_c was finally removed because couldn't find a good shape where growth decreased with increasing VPD
# gmodel <- update(gmodel, . ~ . + VPD_w) # No improvement
# gmodel <- update(gmodel, . ~ . + I(PPT_w^2)) # Not significant
gmodel <- update(gmodel, . ~ . - elev)
summary(gmodel)
growSD <- sd(resid(gmodel))
save(gmodel, growSD, file = "D:/EvansLab/Final/Models/C/grow.rda")
pdf("D:/EvansLab/Final/Output/C/GrowthModel.pdf")
coefplot(gmodel, intercept = F)
preds <- ggpredict(gmodel, terms = c("DRYBIO_AG"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Growth vs. biomass")
# preds <- ggpredict(gmodel, terms = c("elev"))
# ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Growth vs. elevation")
preds <- ggpredict(gmodel, terms = c("PPT_w"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Growth vs. PPT warm")
# preds <- ggpredict(gmodel, terms = c("VPD_c"))
# ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Growth vs. VPD cool")
dev.off()
preds <- ggpredict(gmodel, terms = c("DRYBIO_AG"))
A <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Growth") + xlab("Biomass")
preds <- ggpredict(gmodel, terms = c("PPT_w"))
B <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Growth") + xlab("Warm-season precipitation")
all <- plot_grid(A, B, labels = c("A", "B"), align = "hv")
save_plot("D:/EvansLab/Final/Manuscript/FigS2.png", all, base_aspect_ratio = 1.5)

# Model: size + elevation + BA + climate
gmodel <- lm(data = grdata, GROWTH_INCR ~ DRYBIO_AG + elev + baLive + PPT_c + PPT_w + VPD_c + VPD_w)
gmodel <- update(gmodel, . ~ . - PPT_c)
gmodel <- update(gmodel, . ~ . - VPD_w)
gmodel <- update(gmodel, . ~ . - VPD_c)
gmodel <- update(gmodel, . ~ . + I(DRYBIO_AG^2))
# gmodel <- update(gmodel, . ~ . + I(PPT_w^2))
summary(gmodel)
growSD <- sd(resid(gmodel))
save(gmodel, growSD, file = "D:/EvansLab/Final/Models/BC/grow.rda")
pdf("D:/EvansLab/Final/Output/BC/GrowthModel.pdf")
coefplot(gmodel, intercept = F)
preds <- ggpredict(gmodel, terms = c("DRYBIO_AG"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Growth vs. biomass")
preds <- ggpredict(gmodel, terms = c("elev"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Growth vs. elevation")
preds <- ggpredict(gmodel, terms = c("baLive"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Growth vs. plot BA")
preds <- ggpredict(gmodel, terms = c("PPT_w"))
ggplot(preds, aes(x, predicted)) + geom_line() + ggtitle("Growth vs. PPT warm")
dev.off()
# Publication figures
preds <- ggpredict(gmodel, terms = c("DRYBIO_AG"))
A <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Growth") + xlab("Biomass")
preds <- ggpredict(gmodel, terms = c("elev"))
B <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Growth") + xlab("Elevation")
preds <- ggpredict(gmodel, terms = c("baLive"))
C <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Growth") + xlab("Plot basal area")
preds <- ggpredict(gmodel, terms = c("PPT_w"))
D <- ggplot(preds, aes(x, predicted)) + geom_line() + ylab("Growth") + xlab("Warm-season precipitation")
all <- plot_grid(A, B, C, D, labels = c("A", "B", "C", "D"), align = "hv")
save_plot("D:/EvansLab/Final/Manuscript/FigS3.png", all, base_aspect_ratio = 1.5)
